version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-api-rest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongo:27017/desafio?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./api:/workspace:cached
    working_dir: /workspace
    command: >
      sh -c "mvn clean install -DskipTests && mvn spring-boot:run"

volumes:
  mongo_data:
